#!/bin/bash
set -e
DOT_DIRECTORY="${HOME}/dotfiles"

usage() {
  name=`basename $0`
  cat <<EOF
Usage:
  $name [arguments] [command]
Commands:
  deploy
Arguments:
  -f $(tput setaf 1)** warning **$(tput sgr0) Overwrite dotfiles.
  -h Print help (this message)
EOF
  exit 1
}

while getopts :f:h opt; do
  case ${opt} in
    f)
      OVERWRITE=true
      ;;
    h)
      usage
      ;;
  esac
done
shift $((OPTIND - 1))

# Working only Linux.
case ${OSTYPE} in
  linux-gnu*)
    ;;
  darwin*)
    ;;
  *)
    echo $(tput setaf 1)Working only Linux!!$(tput sgr0)
    exit 1
    ;;
esac

set_symlinks() {
  for f in .??*
  do
    # Force remove the vim directory if it's already there
    [ -n "${OVERWRITE}" -a -e ${HOME}/${f} ] && rm -f ${HOME}/${f}
    if [ ! -e ${HOME}/${f} ]; then
      # If you have ignore files, add file/directory name here
      [[ ${f} = ".git" ]] && continue
      [[ ${f} = ".gitignore" ]] && continue
      ln -snfv ${DOT_DIRECTORY}/${f} ${HOME}/${f}
    fi
  done

  # Creating nvim symlinks
  ln -snfv ${DOT_DIRECTORY}/.vim ${HOME}/.config/nvim

  echo $(tput setaf 2)Link dotfiles symlinks complete! $(tput sgr0)
}

set_git_submodule() {
  git submodule init && git submodule update
  echo $(tput setaf 2)Update git submodules complete! $(tput sgr0)
}

command=$1
[ $# -gt 0 ] && shift

case $command in
  deploy)
    set_symlinks
    set_git_submodule
    ;;
  *)
    usage
    ;;
esac

exit 0
